# Generated by Django 4.0.6 on 2022-07-19 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_followerscount_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerscount',
            name='user',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 16, 57, 48, 862433)),
        ),
    ]
